version: '2'
services:
    studiocity2-app:
        image: studiocity2
        external_links:
            - studiocity2-postgresql:postgresql
            - studiocity2-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/studiocity2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    studiocity2-postgresql:
        extends:
            file: postgresql.yml
            service: studiocity2-postgresql
    studiocity2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: studiocity2-elasticsearch
